### ISSUE TITLE
I can't add new contacts

### ISSUE THREAD

**Issue by ahmedmgh67** [catin-black/meteor-emails#3]
When I try to add a new contact it tells me to "Check your form" and I've filled the required fields

**To Reproduce**
- Clone meteor-emails 
- Run the project as described in the README.MD
- Try to add a new contact

**Expected behavior**
To add the contact to my contacts

**Screenshots**
![image](https://user-images.githubusercontent.com/37451499/83926269-b22eef80-a789-11ea-8d97-80f5f4c85d1f.png)

**Desktop:**
 - OS: MacOS Catalina 10.15.4
 - Browser Chrome
 - Version 83

**Comment by catin-black** [comment]
Thank you for letting know!
I just fixed it and merged to master brach.
Please git pull and let me know if you still have a problem
