### ISSUE TITLE
You have already exceeded the sending limit for today

### ISSUE THREAD

**Issue by Suleman-Elahi** [catin-black/meteor-emails#4]
![image](https://user-images.githubusercontent.com/24384996/84689355-7bfa2880-af5e-11ea-90fd-13e8873e4b01.png)

How can I get rid of this notification? I actually entered a wrong API key in the first attempt. But later when I am trying to send emails with a new API key, it keeps throwing this notification. I have sent only one email that too from SendGrid itself to check if emails are being sent out. But in metero-emails it says you have reached the maximum limit.

My dashboard:
![image](https://user-images.githubusercontent.com/24384996/84689674-ef9c3580-af5e-11ea-9cea-7b155fb5c3a4.png)

**Comment by catin-black** [comment]
I will check what is going on. Thank you

**Comment by catin-black** [comment]
Problem is fixed. Please pull from repository or download the new release.
Now you will be able to send 100 emails per day
