### ISSUE TITLE
Oops, looks like there's no route on the client or the server for url: "http://localhost:3000/." 

### ISSUE THREAD

**Issue by niknah** [catin-black/meteor-emails#9]

**Comment by tstrg** [comment]
I'm facing the same issue.

**Comment by catin-black** [comment]
I will look at it as soon as possible

**Comment by tstrg** [comment]
Hi @catin-black,
Thank you for the fast response. 

I was able to run the app after editing the file meteor/local/build/programs/web.browser/packages/modules.js

I changed the `jQuery` to `jquery` in the following function which comes from 
node_modules/summernote/dist/summernote-bs4.js :

```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')		
                module.exports = factory(require("jquery"));
	else if(typeof define === 'function' && define.amd)
		define(["jquery"], factory);
	else {
		var a = typeof exports === 'object' ? factory(require("jquery")) : factory(root["jquery"]);
		for(var i in a) (typeof exports === 'object' ? exports : root)[i] = a[i];
	}
})
```

I can see the registration page now without any errors in the console. I have not the SendGrid API key yet so cannot confirm all working as expected. 

Hope it helps solve the issue.

**Comment by catin-black** [comment]
I think it was a problem with summernote package.
Please try now and let me know if it's working
